[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = openpg
db_password = openpgpwd
pg_path = C:\Program Files\Odoo 18.0.20241229\PostgreSQL\bin
bin_path = C:\Program Files\Odoo 18.0.20241229\thirdparty
data_dir = c:\Users\Arilano\Downloads\Project ARICE\Project Odoo\clone_data_dir
addons_path = C:\Program Files\Odoo 18.0.20241229\server\odoo\addons, c:\Users\Arilano\Downloads\Project ARICE\Project Odoo\custom_addons
dbfilter = ^Business_Intelegent_Project_v2_fresh_clone$
http_port = 8070
logfile = c:\Users\Arilano\Downloads\Project ARICE\Project Odoo\clone_odoo.log
