[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = openpg
db_password = openpgpwd
pg_path = C:\Program Files\Odoo 18.0.20241229\PostgreSQL\bin
bin_path = C:\Program Files\Odoo 18.0.20241229\thirdparty
data_dir = C:\Program Files\Odoo 18.0.20241229\sessions
addons_path = c:\Users\Arilano\Downloads\Project ARICE\Project Odoo\odoo\addons, c:\Users\Arilano\Downloads\Project ARICE\Project Odoo\custom_addons
dbfilter = ^Business_Intelegent_Project$
