{
    'name': 'OBIDSS Operational Business Intelligence',
    'version': '18.0.1.0.0',
    'category': 'Business Intelligence',
    'summary': 'Custom Operational BI & Decision Support System for PT Prima Alat Nusantara (FY 2026)',
    'author': 'Senior Odoo BI Engineer',
    'website': 'https://github.com/Arilano14/Odoo_Business_Intelligence_Decision_Support_System',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'sale_management',
        'purchase',
        'stock',
        'account',
        'spreadsheet_dashboard',
        'spreadsheet_dashboard_sale',
        'spreadsheet_dashboard_account',
        'spreadsheet_dashboard_stock_account',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'views/obidss_data_quality_views.xml',
        'views/obidss_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
